# Application Name
spring.application.name=EmployeeManagementSystem

# ===========================
# Primary Data Source
# ===========================
spring.datasource.url=jdbc:h2:mem:employeeDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# ===========================
# Secondary Data Source
# ===========================
second.datasource.url=jdbc:h2:mem:departmentDB
second.datasource.driverClassName=org.h2.Driver
second.datasource.username=sa
second.datasource.password=password

# ===========================
# JPA Configuration
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# H2 Console
# ===========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Properties
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.open-in-view=false